map_merge:
  ros__parameters:
    merging_rate: 4.0
    discovery_rate: 0.5
    estimation_rate: 0.5
    estimation_confidence: 0.6
    robot_map_topic: expanded_map
    robot_map_updates_topic: map_updates
    robot_namespace: ""
    merged_map_topic: map
    world_frame: map
    known_init_poses: true
    # known_init_poses: false

    # Define here robots' positions in the map if known_init_poses is true
    /follower/map_merge/init_pose_x: -1.0
    /follower/map_merge/init_pose_y: -1.5
    /follower/map_merge/init_pose_z: 0.01
    /follower/map_merge/init_pose_yaw: 0.0

    /leader/map_merge/init_pose_x: -2.0
    /leader/map_merge/init_pose_y: -0.5
    /leader/map_merge/init_pose_z: 0.01
    /leader/map_merge/init_pose_yaw: 0.0